#!/bin/bash

ROOT=$HOME/.local/zig
REPO_URL=https://ziglang.org/download/index.json
TMPDIR=/tmp/zig

REPO_ENTRY=$1

function die()
{
	echo "$@"
	rm -r ${TMPDIR}
	exit 1
}

if [ ! -d "${ROOT}" ]; then
	echo "Root directory ${ROOT} does not exist!"
	exit 1
fi

REPO="${TMPDIR}/zig-repo.json"

mkdir -p "${TMPDIR}"

echo "Downloading repository..."

curl -s "${REPO_URL}" | jq ".master[\"${REPO_ENTRY}\"]" > "${REPO}" || die "failed to aquire repo!"

TARBALL=$(jq --raw-output '.tarball' ${REPO})
SHASUM=$(jq --raw-output '.shasum' ${REPO})
SIZE=$(jq --raw-output '.size' ${REPO})

VERSION=$(basename ${TARBALL} | sed 's/.tar.xz$//')

[ "${VERSION}" != "" ] || die "Could not extract version info"

if [ -d "${ROOT}/ver/${VERSION}" ]; then
	echo "${VERSION} is already the current version!"
else
	echo "Updating to ${VERSION}"

	if curl "${TARBALL}" | tar -xJC ${ROOT}/ver; then
		rm "${ROOT}/current" || die "failed to set new symlink!"
		ln -s "${ROOT}/ver/${VERSION}" "${ROOT}/current" || die "failed to set new symlink!"
	else
		echo "Update failed!"
		rm -rf "${ROOT}/ver/${VERSION}"
	fi
fi

echo "Current version is now: $($HOME/.local/zig/current/zig version)"

rm -r ${TMPDIR}
