#!/bin/bash

ROOT=$HOME/.local/zig
REPO_URL=https://ziglang.org/download/index.json
TMPDIR=/tmp/zig
SCRIPT_NAME=$(basename "$0")

REPO_ENTRY=$1

function die()
{
	echo "$@"
	rm -r ${TMPDIR}
	exit 1
}

[ -z "${1}" ] && die "Usage: ${SCRIPT_NAME} arch\n Arch according to ${REPO_URL}"

mkdir -p "$ROOT/ver"

REPO="${TMPDIR}/zig-repo.json"

mkdir -p "${TMPDIR}"

echo "Downloading repository..."

curl -s "${REPO_URL}" | jq ".master[\"${REPO_ENTRY}\"]" > "${REPO}" || die "failed to aquire repo!"

TARBALL=$(jq --raw-output '.tarball' ${REPO})
SHASUM=$(jq --raw-output '.shasum' ${REPO})
SIZE=$(jq --raw-output '.size' ${REPO})

VERSION=$(basename ${TARBALL} .tar.xz)

echo "$TARBALL"
echo "$VERSION"

[ "${VERSION}" != "" ] || die "Could not extract version info"

if [ -d "${ROOT}/ver/${VERSION}" ]; then
	echo "${VERSION} is already the current version!"
else
	echo "Updating to ${VERSION}"

	if curl "${TARBALL}" | tar -xJC ${ROOT}/ver; then
		ln -sfn "${ROOT}/ver/${VERSION}" "${ROOT}/current" || die "failed to set new symlink!"
	else
		echo "Update failed!"
		rm -rf "${ROOT}/ver/${VERSION}"
	fi
fi

echo "Current version is now: $($HOME/.local/zig/current/zig version)"
echo "Add \$HOME/.local/zig/current to your PATH"

rm -r ${TMPDIR}
